### ISSUE TITLE
Issues in building TensorSwarm

### ISSUE THREAD

**Issue by jtrautmann** [TensorSwarm/TensorSwarm#3]
Hi,

I followed the installation instructions. I built and installed Argos from the corresponding branch. The only difference is that I have Melodic installed instead of Kinetic. I tried to  build TensorSwarm, but I get the following errors:

```
CMake Error at TensorSwarm/plugin/CMakeLists.txt:12 (include):
  include could not find load file:

    ARGoSCheckQTOpenGL


CMake Error at TensorSwarm/plugin/CMakeLists.txt:15 (find_package):
  By not providing "FindLua52.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Lua52", but
  CMake did not find one.

  Could not find a package configuration file provided by "Lua52" with any of
  the following names:

    Lua52Config.cmake
    lua52-config.cmake

  Add the installation prefix of "Lua52" to CMAKE_PREFIX_PATH or set
  "Lua52_DIR" to a directory containing one of the above files.  If "Lua52"
  provides a separate development package or SDK, be sure it has been
  installed.
```

Do you maybe have any idea what the problem could be?

Thank you

**Comment by jtrautmann** [comment]
I fixed this. I already had the [argos_bridge](https://github.com/BOTSlab/argos_bridge) package added to my workspace and as they both build a library named `argos_ros_bot`, that seems to have been the problem. After deleting the `build` and `devel` directories and excluding `argos_bridge`, I had no problems anymore in building TensorSwarm.

**Comment by deeplearningrobotics** [comment]
@jtrautmann: Great that you could resolve it. Let me know if you need anything else!

**Comment by BenjaminOgden88** [comment]
> I fixed this. I already had the [argos_bridge](https://github.com/BOTSlab/argos_bridge) package added to my workspace and as they both build a library named `argos_ros_bot`, that seems to have been the problem. After deleting the `build` and `devel` directories and excluding `argos_bridge`, I had no problems anymore in building TensorSwarm.

Do you have any suggestions on where I should go in the Argos project to exclude the argos_bridge build?
